---
- hosts: leader
  gather_facts: no
  tasks:

    - name: install cephfs cluster
      shell: cephadm bootstrap --mon-ip {{ ansible_default_ipv4.address }} &> info.log
      args:
        executable: /bin/bash
        creates: info.log

    - name: get ceph ssh key
      shell: cat /etc/ceph/ceph.pub
      register: ssh_key

- hosts: followers
  gather_facts: no
  tasks:

     - name: deploy ceph ssh key to all nodes
       authorized_key:
         user: "root"
         key: "{{ hostvars[groups['leader'][0]]['ssh_key'].stdout }}"

- hosts: leader
  gather_facts: no
  tasks:

     - name: add nodes to cluster
       shell: ceph orch host add {{ item }}
       loop: '{{ groups["followers"] }}'

     - name: create mon
       shell: ceph orch apply mon 3

     - name: apply mon
       vars:
         node_list: "{{ groups['all']|join(',') }}"
       shell: ceph orch apply mon {{ node_list }}

     - name: Retry device ls until all mons are up - Be patient...
       shell: ceph orch device ls
       register: osd_test
       until: item is in osd_test.stdout
       loop: "{{ query('inventory_hostnames', 'all') }}"
       retries: 60
       delay: 5

     - name: extract osds
       shell: ceph orch device ls | grep -v 'locked' | grep '/dev' | awk '{print $1":"$2}'
       register: osds

     - name: create osds
       shell: |
         ceph orch daemon add osd {{ item }}
         sleep 2
       loop: "{{ osds.stdout_lines }}"

     - name: add all disks
       shell: ceph orch apply osd --all-available-devices

     - name: restart ceph to get health ok
       #https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/message/RLVSPF6FWLK4JSSAQJBVFJ6SITJLEMCS/
       shell: ceph -s
