---
- hosts: main
  gather_facts: no
  tasks:

    - name: install cephfs cluster
      shell: cephadm bootstrap --mon-ip {{ ansible_default_ipv4.address }} &> info.log
      args:
        executable: /bin/bash
        creates: info.log

    - name: get ceph ssh key
      shell: cat /etc/ceph/ceph.pub
      register: ssh_key

- hosts: all,!main
  gather_facts: no
  tasks:

     - name: deploy ceph ssh key to all nodes
       authorized_key:
         user: "root"
         key: "{{ hostvars[groups['main'][0]]['ssh_key'].stdout }}"

- hosts: main
  tasks:


     - name: add nodes to cluster
       shell: ceph orch host add {{ item }}
       loop: '{{ groups["all"] }}'
       when: not item == inventory_hostname

     - name: create mon
       shell: ceph orch apply mon 3

     - name: apply mon
       vars:
         node_list: "{{ groups['all']|join(',') }}"
       shell: ceph orch apply mon {{ node_list }}

     - name: add all disks
       shell: ceph orch apply osd --all-available-devices
