---
- hosts: main
  become: yes
  gather_facts: no
  tasks:

    - name: install cephfs cluster
      shell: cephadm bootstrap --mon-ip {{ ansible_default_ipv4.address }} &> info.log
      args:
        executable: /bin/bash
